name = "ManufacturedSolutions"
uuid = "46fab770-a24b-40c2-a49c-65d2c37a0689"
authors = ["Marvyn Bailly <marvyn@marvyn.com>"]
version = "0.1.0" 
repo = "https://github.com/MarvynBailly/ManufacturedSolutions.jl"

[compat]
julia = "1.10.4"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]