/*
 * Simple 1D Poisson Solver
 * Solves: -d²u/dx² = f(x) on [0,1] with Dirichlet BCs
 * 
 * To use with MMS:
 * - The forcing function f(x) will be injected at the marker below
 * - Results are written to "solution.txt"
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// Grid parameters (will be replaced by MMS tool)
#ifndef NX
#define NX 51
#endif

/* AUTO-GENERATED by ManufacturedSolutions.jl */
/* Forcing term for manufactured solution verification */
double forcing(double x) {
    return 9.869604401089358*sin(M_PI*x);
}

// MMS_FORCING_FUNCTION_HERE
// Default: constant forcing (will be replaced by MMS tool)
double forcing(double x) {
    return 1.0;
}

// Boundary conditions
double bc_left() {
    return 0.0;
}

double bc_right() {
    return 0.0;
}

// Solve -u'' = f(x) using finite differences
void solve_poisson(int nx, double *x, double *u, double *f) {
    double h = 1.0 / (nx - 1);
    double h2 = h * h;
    
    // Allocate tridiagonal system
    double *a = (double*)malloc(nx * sizeof(double));
    double *b = (double*)malloc(nx * sizeof(double));
    double *c = (double*)malloc(nx * sizeof(double));
    double *rhs = (double*)malloc(nx * sizeof(double));
    
    // Set up tridiagonal system
    // -u_{i-1} + 2*u_i - u_{i+1} = h^2 * f_i
    for (int i = 0; i < nx; i++) {
        if (i == 0) {
            // Left boundary
            a[i] = 0.0;
            b[i] = 1.0;
            c[i] = 0.0;
            rhs[i] = bc_left();
        } else if (i == nx - 1) {
            // Right boundary
            a[i] = 0.0;
            b[i] = 1.0;
            c[i] = 0.0;
            rhs[i] = bc_right();
        } else {
            // Interior points
            a[i] = -1.0;
            b[i] = 2.0;
            c[i] = -1.0;
            rhs[i] = h2 * f[i];
        }
    }
    
    // Thomas algorithm (tridiagonal solver)
    // Forward elimination
    for (int i = 1; i < nx; i++) {
        double m = a[i] / b[i-1];
        b[i] = b[i] - m * c[i-1];
        rhs[i] = rhs[i] - m * rhs[i-1];
    }
    
    // Back substitution
    u[nx-1] = rhs[nx-1] / b[nx-1];
    for (int i = nx - 2; i >= 0; i--) {
        u[i] = (rhs[i] - c[i] * u[i+1]) / b[i];
    }
    
    // Free memory
    free(a);
    free(b);
    free(c);
    free(rhs);
}

int main() {
    int nx = NX;
    double h = 1.0 / (nx - 1);
    
    // Allocate arrays
    double *x = (double*)malloc(nx * sizeof(double));
    double *u = (double*)malloc(nx * sizeof(double));
    double *f = (double*)malloc(nx * sizeof(double));
    
    // Generate grid
    for (int i = 0; i < nx; i++) {
        x[i] = i * h;
    }
    
    // Evaluate forcing function
    for (int i = 0; i < nx; i++) {
        f[i] = forcing(x[i]);
    }
    
    // Solve
    solve_poisson(nx, x, u, f);
    
    // Write results
    FILE *fp = fopen("solution.txt", "w");
    if (fp == NULL) {
        fprintf(stderr, "Error opening output file\n");
        return 1;
    }
    
    fprintf(fp, "# x u\n");
    for (int i = 0; i < nx; i++) {
        fprintf(fp, "%.15e %.15e\n", x[i], u[i]);
    }
    
    fclose(fp);
    
    // Free memory
    free(x);
    free(u);
    free(f);
    
    printf("Solution written to solution.txt\n");
    printf("Grid points: %d\n", nx);
    
    return 0;
}
