"""
Minimal test of code injection functionality
"""

using Printf

# Load code injection directly
include(joinpath(@__DIR__, "..", "src", "codegen", "code_injection.jl"))

println("Testing code injection with C Poisson solver...")
println()

# Test generating C code
println("Test 1: Generate C code")
println("-" ^ 50)

# Simplified forcing term
forcing_code = """/* AUTO-GENERATED by ManufacturedSolutions.jl */
double forcing_term(double x) {
    return 9.8696 * sin(3.14159 * x);
}
"""

println("Generated forcing function:")
println(forcing_code)
println()

# Test injection
println("Test 2: Inject into C file")
println("-" ^ 50)

source_file = joinpath(@__DIR__, "c_code", "poisson_solver.c")
output_file = joinpath(@__DIR__, "c_code", "poisson_solver_mms.c")

println("Source: $source_file")
println("Output: $output_file")
println("File exists: $(isfile(source_file))")
println()

if isfile(source_file)
    marker_found = inject_forcing_code(source_file, forcing_code, output_file)
    
    if marker_found
        println("✓ Code injected successfully at marker location")
    else
        println("⚠ Marker not found - code appended to end")
    end
    
    println("✓ Modified file written to: $output_file")
    println()
    
    # Verify the injection
    println("Test 3: Verify injection")
    println("-" ^ 50)
    
    content = read(output_file, String)
    lines = split(content, '\n')
    
    for (i, line) in enumerate(lines)
        if occursin("forcing_term", line) && i > 20  # Skip the original function
            println("Found injected function at line $i:")
            for j in i:min(i+3, length(lines))
                println("  ", lines[j])
            end
            break
        end
    end
    
    println()
    println("="^70)
    println("Code injection test successful!")
    println("="^70)
else
    println("ERROR: Source file not found!")
    println("Looking in: $source_file")
end
