"""
Code generation and injection for forcing terms

This module generates forcing function code in various languages
and injects it into user's solver files.
"""

"""
    CodeTemplate

Represents a code template for a specific programming language.
"""
struct CodeTemplate
    language::Symbol  # :julia, :c, :python, :fortran
    function_template::String
    injection_marker::String
end

# Default templates for common languages
const JULIA_TEMPLATE = CodeTemplate(
    :julia,
    """
    # AUTO-GENERATED by ManufacturedSolutions.jl
    # Forcing term for manufactured solution verification
    function forcing_term(ARGS)
        return EXPRESSION
    end
    """,
    "# MMS_FORCING_FUNCTION_HERE"
)

const C_TEMPLATE = CodeTemplate(
    :c,
    """
    /* AUTO-GENERATED by ManufacturedSolutions.jl */
    /* Forcing term for manufactured solution verification */
    double forcing(ARGS) {
        return EXPRESSION;
    }
    """,
    "// MMS_FORCING_FUNCTION_HERE"
)

const PYTHON_TEMPLATE = CodeTemplate(
    :python,
    """
    # AUTO-GENERATED by ManufacturedSolutions.jl
    # Forcing term for manufactured solution verification
    def forcing_term(ARGS):
        return EXPRESSION
    """,
    "# MMS_FORCING_FUNCTION_HERE"
)

const FORTRAN_TEMPLATE = CodeTemplate(
    :fortran,
    """
    ! AUTO-GENERATED by ManufacturedSolutions.jl
    ! Forcing term for manufactured solution verification
    function forcing_term(ARGS) result(f)
        DECLARATIONS
        f = EXPRESSION
    end function forcing_term
    """,
    "! MMS_FORCING_FUNCTION_HERE"
)

"""
    generate_forcing_code(forcing_term::ForcingTerm, language::Symbol, args::Vector{Symbol})

Generate forcing function code in the specified language.

# Arguments
- `forcing_term::ForcingTerm`: Forcing term from symbolic computation
- `language::Symbol`: Target language (:julia, :c, :python, :fortran)
- `args::Vector{Symbol}`: Argument names (e.g., [:x, :t])

# Returns
- `String`: Generated code
"""
function generate_forcing_code(forcing_term::ForcingTerm, language::Symbol, args::Vector{Symbol})
    template = get_template(language)
    
    # Convert symbolic expression to target language
    expr_str = symbolic_to_code(forcing_term.symbolic_form, language)
    args_str = join(string.(args), ", ")
    
    # For C and Fortran, we need type declarations
    if language == :c
        args_str = join(["double " * string(arg) for arg in args], ", ")
    elseif language == :fortran
        declarations = join(["    real(8) :: " * string(arg) for arg in args], "\n")
        code = replace(template.function_template, "DECLARATIONS" => declarations)
        code = replace(code, "ARGS" => args_str)
        code = replace(code, "EXPRESSION" => expr_str)
        return code
    end
    
    # Generate code
    code = replace(template.function_template, "ARGS" => args_str)
    code = replace(code, "EXPRESSION" => expr_str)
    
    return code
end

"""
    get_template(language::Symbol)

Get the code template for a specific language.
"""
function get_template(language::Symbol)
    if language == :julia
        return JULIA_TEMPLATE
    elseif language == :c
        return C_TEMPLATE
    elseif language == :python
        return PYTHON_TEMPLATE
    elseif language == :fortran
        return FORTRAN_TEMPLATE
    else
        error("Unsupported language: $language. Supported: :julia, :c, :python, :fortran")
    end
end

"""
    symbolic_to_code(expr, language::Symbol)

Convert a symbolic expression to code in the target language.

# Arguments
- `expr`: Symbolic expression (from Symbolics.jl)
- `language::Symbol`: Target language

# Returns
- `String`: Code expression
"""
function symbolic_to_code(expr, language::Symbol)
    # Convert to string first
    expr_str = string(expr)
    
    if language == :julia
        # Julia syntax is mostly compatible with symbolic output
        return cleanup_julia_expr(expr_str)
        
    elseif language == :c
        # C syntax conversions
        # First replace π with M_PI before other replacements
        expr_str = replace(expr_str, "π" => "M_PI")
        # Add explicit multiplication between M_PI and variables
        expr_str = replace(expr_str, r"M_PI([a-z])" => s"M_PI*\1")
        # Handle implicit multiplication for numbers and variables
        expr_str = replace(expr_str, r"(\d+\.?\d*)([a-z])" => s"\1*\2")
        # Handle power operations (must be after other replacements)
        # This is complex - for now we don't handle it
        # Replace math functions
        expr_str = replace_math_functions_c(expr_str)
        return expr_str
        
    elseif language == :python
        # Python syntax (similar to Julia but with **)
        expr_str = replace(expr_str, "^" => "**")
        expr_str = replace(expr_str, "π" => "math.pi")
        expr_str = cleanup_julia_expr(expr_str)
        return expr_str
        
    elseif language == :fortran
        # Fortran syntax
        expr_str = replace(expr_str, "^" => "**")
        expr_str = replace(expr_str, "π" => "4.0d0*datan(1.0d0)")  # Fortran way to get π
        expr_str = replace_math_functions_fortran(expr_str)
        return expr_str
    end
    
    return expr_str
end

"""
    cleanup_julia_expr(expr_str::String)

Clean up symbolic expression for Julia code.
"""
function cleanup_julia_expr(expr_str::String)
    # Add explicit multiplication between π and variables
    expr_str = replace(expr_str, r"π([a-z])" => s"π*\1")
    # Add explicit multiplication between numbers and variables
    expr_str = replace(expr_str, r"(\d+\.?\d*)([a-z])" => s"\1*\2")
    return expr_str
end

"""
    replace_math_functions_c(expr_str::String)

Replace Julia math functions with C equivalents.
"""
function replace_math_functions_c(expr_str::String)
    # Common math function mappings
    expr_str = replace(expr_str, r"\bsin\b" => "sin")
    expr_str = replace(expr_str, r"\bcos\b" => "cos")
    expr_str = replace(expr_str, r"\bexp\b" => "exp")
    expr_str = replace(expr_str, r"\bsqrt\b" => "sqrt")
    expr_str = replace(expr_str, r"\blog\b" => "log")
    # Add pow for exponentiation if needed
    # This is complex - may need a proper parser
    return expr_str
end

"""
    replace_math_functions_fortran(expr_str::String)

Replace Julia math functions with Fortran equivalents.
"""
function replace_math_functions_fortran(expr_str::String)
    # Fortran uses uppercase or d-versions for double precision
    expr_str = replace(expr_str, r"\bsin\b" => "dsin")
    expr_str = replace(expr_str, r"\bcos\b" => "dcos")
    expr_str = replace(expr_str, r"\bexp\b" => "dexp")
    expr_str = replace(expr_str, r"\bsqrt\b" => "dsqrt")
    expr_str = replace(expr_str, r"\blog\b" => "dlog")
    return expr_str
end

"""
    inject_forcing_code(
        source_file::String,
        forcing_code::String,
        output_file::String;
        marker::String="MMS_FORCING"
    )

Inject generated forcing code into a source file.

# Arguments
- `source_file::String`: Path to original solver code
- `forcing_code::String`: Generated forcing function code
- `output_file::String`: Path to write modified code
- `marker::String`: Marker string to find injection point (default: "MMS_FORCING")

# Example
```julia
# In user's C code, they place:
// MMS_FORCING_FUNCTION_HERE

# This function finds that marker and injects the forcing code
inject_forcing_code("solver.c", forcing_code, "solver_mms.c")
```
"""
function inject_forcing_code(
    source_file::String,
    forcing_code::String,
    output_file::String;
    marker::String="MMS_FORCING"
)
    # Read the source file
    if !isfile(source_file)
        error("Source file not found: $source_file")
    end
    
    source_content = read(source_file, String)
    
    # Find the marker
    # Support different comment styles
    markers = [
        "// $(marker)_FUNCTION_HERE",      # C/C++/Julia
        "# $(marker)_FUNCTION_HERE",       # Python/Julia
        "! $(marker)_FUNCTION_HERE",       # Fortran
        "/* $(marker)_FUNCTION_HERE */",   # C block comment
    ]
    
    marker_found = false
    modified_content = source_content
    
    for m in markers
        if occursin(m, source_content)
            # Inject the code right before the marker (keeps marker for future runs)
            modified_content = replace(source_content, m => forcing_code * "\n" * m)
            marker_found = true
            break
        end
    end
    
    if !marker_found
        @warn "Marker not found in source file. Supported markers: $markers"
        @warn "Appending forcing code to end of file."
        modified_content = source_content * "\n\n" * forcing_code
    end
    
    # Write to output file
    write(output_file, modified_content)
    
    return marker_found
end

"""
    create_solver_template(language::Symbol, output_file::String)

Create a template solver file with MMS markers for the given language.

This helps users get started by showing where to place markers.
"""
function create_solver_template(language::Symbol, output_file::String)
    template = get_template(language)
    
    content = """
    # ================================================================
    # MMS Verification Template for $(uppercase(string(language)))
    # ================================================================
    # 
    # This template shows where to place MMS markers in your code.
    # 
    # Instructions:
    # 1. Place $(template.injection_marker) where the forcing function should be generated
    # 2. In your solver, call forcing_term(x) or forcing_term(x, t)
    # 3. Run MMS verification to automatically generate and inject the forcing code
    #
    # ================================================================
    
    $(template.injection_marker)
    
    # Your solver code goes here
    # Make sure to call forcing_term() in the appropriate place
    """
    
    write(output_file, content)
    @info "Created MMS template: $output_file"
end

export CodeTemplate, generate_forcing_code, inject_forcing_code
export create_solver_template, get_template
